import { useState } from "react";
import type { GameId, GameConfig } from "../types/game";
import type { LearnerProfile } from "../types/learner";
import { GAMES } from "../config/games";
import { LANGUAGES } from "../config/languages";
import { GameCard } from "../components/GameCard";
import { LearnerBadge } from "../components/LearnerBadge";
import { SettingsPanel } from "../components/SettingsPanel";

interface Props {
  profile: LearnerProfile;
  onSelectGame: (id: GameId) => void;
  onUpdateProfile: (profile: LearnerProfile) => void;
}

export function HomeScreen({ profile, onSelectGame, onUpdateProfile }: Props) {
  const [settingsOpen, setSettingsOpen] = useState(false);
  const lang = LANGUAGES.find((l) => l.value === profile.language);

  return (
    <div className="h-screen bg-[#080a0f] flex flex-col overflow-hidden">
      {/* Header */}
      <header className="flex-shrink-0 flex items-center justify-between px-6 py-4 border-b border-white/[0.05]">
        <div className="flex items-center gap-2">
          <span className="text-lg">🌙</span>
          <span className="font-serif italic text-[var(--text-1)] text-lg">Luma</span>
        </div>
        <LearnerBadge profile={profile} onEdit={() => setSettingsOpen(true)} />
      </header>

      {/* Body */}
      <div className="flex-1 overflow-y-auto px-6 py-8">
        {/* Greeting */}
        <div className="mb-8 animate-fade-up">
          <h2 className="text-2xl font-semibold text-[var(--text-1)] mb-1">
            Ready to practice?
          </h2>
          <p className="text-sm text-[var(--text-2)]">
            Choose a game and your AI tutor will generate content in{" "}
            <span className="text-[var(--text-1)]">
              {lang?.flag} {lang?.label}
            </span>{" "}
            at level{" "}
            <span className="text-[var(--text-1)]">{profile.level}</span>.
          </p>
        </div>

        {/* Game Grid */}
        <div className="grid grid-cols-1 gap-3">
          {GAMES.map((game: GameConfig, i: number) => (
            <div
              key={game.id}
              className="animate-fade-up"
              style={{ animationDelay: `${i * 80}ms` }}
            >
              <GameCard game={game} onClick={() => onSelectGame(game.id)} />
            </div>
          ))}
        </div>

        <p className="text-center text-xs text-[var(--text-3)] mt-8">
          Content generated by local AI · stays on your device
        </p>
      </div>

      {/* Settings */}
      {settingsOpen && (
        <SettingsPanel
          profile={profile}
          onSave={onUpdateProfile}
          onClose={() => setSettingsOpen(false)}
        />
      )}
    </div>
  );
}